---
title: "Study 1 Analysis"
author: "Bryan Hee"
date: "March 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(xts)
library(highfrequency)
library(lubridate)
library(readxl)
library(devtools)
```

```{r load_data}
Temp_Conf2 <- read_excel("C:/Users/BryanHee/OneDrive - stok LLC/Senseware/Data Processing/Upstairs Conference Room/Raw Data/temperature-upstairs-conference.xlsx", col_types = c("date", "numeric", "numeric", "numeric", "numeric", "numeric"))
  
RH_Conf2 <- read_excel("C:/Users/BryanHee/OneDrive - stok LLC/Senseware/Data Processing/Upstairs Conference Room/Raw Data/Humidity.xlsx", col_types = c("date", "numeric", "numeric", "numeric"))

CO2_Conf2 <- read_excel("C:/Users/BryanHee/OneDrive - stok LLC/Senseware/Data Processing/Upstairs Conference Room/Raw Data/CO2.xlsx", col_types = c("date", "numeric", "numeric", "numeric"))

IAQ_Conf2 <- read_excel("C:/Users/BryanHee/OneDrive - stok LLC/Senseware/Data Processing/Upstairs Conference Room/Raw Data/VOC.xlsx", col_types = c("date", "numeric", "numeric","numeric", "numeric", "numeric"))

glimpse(CO2_Conf2)
glimpse(RH_Conf2)
glimpse(Temp_Conf2)
glimpse(IAQ_Conf2)
```

```{r Temp 15 Min}
Temp_dt <- Temp_Conf2$DateTime
Temp_xts = xts(Temp_Conf2, order.by = Temp_dt)
Temp_xts$DateTime <- NULL
my_mean <- function(x){
  mean(as.numeric(x), na.rm = TRUE)
}
Temp_Conf2_15m = aggregatets(Temp_xts, FUN = "my_mean", on = "minutes", k = 15)
rm(Temp_Conf2, Temp_xts, Temp_dt)
```

```{r RH 15 Min}
RH_dt <- RH_Conf2$DateTime
RH_xts = xts(RH_Conf2, order.by = RH_dt)
RH_xts$DateTime <- NULL
my_mean = function(x){
  mean(as.numeric(x), na.rm=TRUE)
  }
RH_Conf2_15m = aggregatets(RH_xts, FUN = "my_mean", on = "minutes", k = 15)
rm(RH_Conf2, RH_dt, RH_xts)
```

```{r CO2 15 Min}
CO2_dt <- CO2_Conf2$DateTime
CO2_xts = xts(CO2_Conf2, order.by = CO2_dt)
CO2_xts$DateTime <- NULL
my_mean = function(x){mean(as.numeric(x), na.rm=TRUE)}
CO2_Conf2_15m = aggregatets(CO2_xts, FUN = "my_mean", on = "minutes", k = 15)
rm(CO2_dt, CO2_xts, CO2_Conf2)
```

```{r IAQ 15 Min}
IAQ_Conf2_15m_xts = xts(IAQ_Conf2, order.by = as.POSIXct(IAQ_Conf2$DateTime, format = "%m-%d-%y %H:%M"))
IAQ_Conf2_15m_xts$DateTime <- NULL
```

```{r rename column names}
names(Temp_Conf2_15m) <- c("Table_dB", "Ceiling_dB", "Open_Office_dB", "Weather_dB", "Weather_Dew_Point")
names(RH_Conf2_15m) <- c("Table_RH", "Ceiling_RH", "Weather_RH")
```

```{r Adding Columns NOT USED YET}
IAQ_Conf2 <- mutate(IAQ_Conf2, month = month(DateTime),
                    day = day(DateTime),
                    year = year(DateTime),
                    week = week(DateTime))
RH_Conf2_15m <- mutate(RH_Conf2_15m, month = month(RH_Conf2_15m[0]))
      #              day = day(DateTime),
       #             year = year(DateTime),
        #            week = week(DateTime))
Temp_Conf2_15m <- mutate(Temp_Conf2_15m, month = month(DateTime),
                    day = day(DateTime),
                    year = year(DateTime),
                    week = week(DateTime))
CO2_Conf2_15m <- mutate(CO2_Conf2_15m, month = month(DateTime),
                    day = day(DateTime),
                    year = year(DateTime),
                    week = week(DateTime))
```

```{r Psych echo=FALSE, message=FALSE}
library(climateeng)
  
dB_RH <- as.data.frame(Temp_Conf2_15m[,1])
hum.ratio <- as.data.frame(RH_Conf2_15m[,1])
dB_RH[,2] <- hum.ratio[,1]
colnames(dB_RH)[2] <- "Table_RH"
rm(hum.ratio)
str(dB_RH)

psychrometric_chart(temp.db =dB_RH[,1], hum.ratio = dB_RH[,2], alpha = 1)

#psychrometric_chart(temp.db, hum.ratio, temp.min=5, mollier = TRUE,
# alpha = 1)
```


